### PR TITLE
:broom: some necessary maintenance

### LINKED ISSUE #79: :broom: add formatting & linting checks to CI-CD
-> serve this functionality through a `Makefile`

### PR DESCRIPTION
**Pull request by jvdd**
- [x] :arrow_up: update the `tsfresh` (dev) dependency, fixing the issue with installing `matrixprofile` https://github.com/blue-yonder/tsfresh/pull/985
- [x] :broom: remove LGTM badge from `README.md`
- [x] add linting: ruff
- [x] add formatting: black + isort
- [x] add `Makefile`
- [x] check formatting & linting in CI-CD, resolves #79 
- [x] :handshake: update `CONTRIBUTING.md`

### CODE REVIEW

**Comment by jvdd** [comment]
Ready for review @jonasvdd

**Comment by jonasvdd** [comment]
FYI @jvdd, the logger was only improved for the `seriesprocessor` (and thus not the `FeatureCollection` in #73 )

**Comment by jonasvdd** [comment]
I will review it this evening! 😄

**Review by jonasvdd — APPROVED** [review]
LGTM! nice cleanup!

**Comment by jvdd** [comment]
@jonavdd what would you change to the loger of the `FeatureCollection`?

**Comment by jonasvdd** [comment]
Maybe also show the duration in `%`, less mental effort to interpret the timings 😄 ?  (as we did in #73)

**Pull request merged**
